In [4]:
import h5py
import numpy as np
import matplotlib.pyplot as plt

In [5]:
ls *.hdf5

CC.hdf5    RNAi.hdf5  ac.hdf5    foo.hdf5   t.hdf5


In [6]:
f = h5py.File('test.hdf5','w')
f

<HDF5 file "test.hdf5" (mode r+)>

In [7]:
f.name

'/'

In [8]:
list(f.keys())

[]

In [9]:
grp = f.create_group("grp1")
grp

<HDF5 group "/grp1" (0 members)>

In [10]:
subgrp = grp.create_group("subgrp1")
subgrp

<HDF5 group "/grp1/subgrp1" (0 members)>

In [11]:
grp

<HDF5 group "/grp1" (1 members)>

In [12]:
del grp['subgrp1']

In [13]:
grp

<HDF5 group "/grp1" (0 members)>

In [14]:
test_data = np.array(np.random.randn(10000, 1000), dtype=np.float64)
test_data

array([[-0.6629369 , -0.083222  ,  0.78678465, ..., -0.60402045,
         0.30921621,  0.32274223],
       [ 1.65684941,  1.81157478, -0.58112347, ..., -0.8266425 ,
        -0.14968202, -0.70237102],
       [-1.09869976,  1.20535342,  0.58283724, ..., -1.96606708,
         0.67811401,  1.41829879],
       ...,
       [ 0.12738114, -0.70627814,  1.9276564 , ...,  1.00978219,
         0.81511658, -0.75722884],
       [-0.71374493, -0.21506902, -1.49835381, ..., -1.42165749,
        -2.4525693 , -0.96614514],
       [-0.87216783,  0.76681657, -0.83032781, ...,  0.88566248,
         0.62789108,  0.37365516]])

In [15]:
f.create_dataset('data', data=test_data)

<HDF5 dataset "data": shape (10000, 1000), type "<f8">

In [16]:
f.create_dataset('grp2/data', data=test_data)

<HDF5 dataset "data": shape (10000, 1000), type "<f8">

In [17]:
f.keys()

<KeysViewHDF5 ['data', 'grp1', 'grp2']>

In [ ]:
f['grp2']['data']

In [ ]:
### Data Slicing

In [18]:
%%time
f['grp2']['data']

CPU times: user 1.82 ms, sys: 1.89 ms, total: 3.71 ms
Wall time: 5.12 ms


<HDF5 dataset "data": shape (10000, 1000), type "<f8">

In [43]:
%%time
f['grp2']['data'][:10]

CPU times: user 1.54 ms, sys: 317 µs, total: 1.86 ms
Wall time: 4.16 ms


array([[-0.6629369 , -0.083222  ,  0.78678465, ..., -0.60402045,
         0.30921621,  0.32274223],
       [ 1.65684941,  1.81157478, -0.58112347, ..., -0.8266425 ,
        -0.14968202, -0.70237102],
       [-1.09869976,  1.20535342,  0.58283724, ..., -1.96606708,
         0.67811401,  1.41829879],
       ...,
       [ 0.31260315, -2.8429931 , -0.11119945, ...,  0.89681444,
        -1.435853  , -0.18240694],
       [ 0.17298251, -0.21348632, -0.50641505, ..., -0.85435628,
        -1.02027907,  0.37475804],
       [-0.81741549,  1.33193152, -0.74258592, ..., -0.09692635,
        -1.17859348, -1.03134472]])

In [46]:
%%timeit
f['grp2']['data'][10]

84.7 µs ± 559 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [21]:
%%time
f['grp2']['data'][:1000]

CPU times: user 2.49 ms, sys: 5.13 ms, total: 7.62 ms
Wall time: 9.5 ms


array([[-0.6629369 , -0.083222  ,  0.78678465, ..., -0.60402045,
         0.30921621,  0.32274223],
       [ 1.65684941,  1.81157478, -0.58112347, ..., -0.8266425 ,
        -0.14968202, -0.70237102],
       [-1.09869976,  1.20535342,  0.58283724, ..., -1.96606708,
         0.67811401,  1.41829879],
       ...,
       [-1.41801451, -1.50522127,  0.32751112, ...,  1.46775141,
        -1.61606727,  0.01151317],
       [ 0.36102929,  0.2398204 ,  0.45041452, ...,  0.60286495,
        -0.12738818, -0.56043784],
       [ 1.32267552,  0.99309706,  1.03991064, ..., -0.90981611,
         1.40484222, -0.54803533]])

In [22]:
%%time
f['grp2']['data'][::100]

CPU times: user 2.49 ms, sys: 4.58 ms, total: 7.07 ms
Wall time: 5.93 ms


array([[-0.6629369 , -0.083222  ,  0.78678465, ..., -0.60402045,
         0.30921621,  0.32274223],
       [-0.23647256, -0.32839387,  1.20884966, ..., -0.68169262,
        -0.07326177,  0.06880493],
       [-0.79423517, -1.14075143, -1.92140488, ..., -1.1545242 ,
        -1.59933867, -1.04918633],
       ...,
       [-0.41087465, -1.0627887 , -0.29984161, ...,  2.14829747,
        -0.31672831,  0.56592023],
       [-0.65135049, -0.1830246 ,  0.67046726, ..., -1.63669957,
        -0.44336007, -0.74529049],
       [-0.33468052,  0.32631875,  1.77610411, ..., -0.74030001,
        -0.16700581, -0.4805291 ]])

In [23]:
f.create_dataset("autochunk1", data=test_data, chunks=True)

<HDF5 dataset "autochunk1": shape (10000, 1000), type "<f8">

In [24]:
f.keys()

<KeysViewHDF5 ['autochunk1', 'data', 'grp1', 'grp2']>

In [45]:
%%timeit
f['autochunk1'][:10]

210 µs ± 3.91 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [32]:
f.create_dataset('data_columnwise', shape=(10000, 1000), dtype=np.float64, chunks=(10000, 1), data=test_data)

<HDF5 dataset "data_columnwise": shape (10000, 1000), type "<f8">

In [ ]:
f.keys()

In [ ]:
f.create_dataset("zipped", (100, 100), compression="gzip")